-- MySQL Script generated by MySQL Workbench
-- Fri Apr 16 15:31:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente` (
  `idPaciente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(2) NULL,
  `Edad` INT NOT NULL,
  `Telefono` INT NOT NULL,
  `EPS` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Protesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Protesis` (
  `Serial_protesis` INT NOT NULL AUTO_INCREMENT,
  `Amputacion` VARCHAR(255) NULL,
  `Medidas` LONGTEXT NULL,
  PRIMARY KEY (`Serial_protesis`));


-- -----------------------------------------------------
-- Table `Profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Profesionales` (
  `Nombre` VARCHAR(255) NOT NULL,
  `idProfesionales` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Usuario` VARCHAR(255) NOT NULL,
  `Cargo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idProfesionales`));


-- -----------------------------------------------------
-- Table `Paciente_protesis_profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente_protesis_profesional` (
  `idPaciente_protesis_profesional` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Protesis_Serial_protesis` INT NOT NULL,
  `Profesionales_idProfesionales` INT NOT NULL,
  PRIMARY KEY (`idPaciente_protesis_profesional`),
  INDEX `fk_Paciente_protesis_profesional_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Paciente_protesis_profesional_Protesis1_idx` (`Protesis_Serial_protesis` ASC),
  INDEX `fk_Paciente_protesis_profesional_Profesionales1_idx` (`Profesionales_idProfesionales` ASC),
  CONSTRAINT `fk_Paciente_protesis_profesional_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_protesis_profesional_Protesis1`
    FOREIGN KEY (`Protesis_Serial_protesis`)
    REFERENCES `Protesis` (`Serial_protesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_protesis_profesional_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales`)
    REFERENCES `Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proceso` (
  `Etapa` INT NOT NULL,
  `Descripción` LONGTEXT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Paciente_protesis_profesional_idPaciente_protesis_profesional` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Proceso_Paciente_protesis_profesional1_idx` (`Paciente_protesis_profesional_idPaciente_protesis_profesional` ASC),
  CONSTRAINT `fk_Proceso_Paciente_protesis_profesional1`
    FOREIGN KEY (`Paciente_protesis_profesional_idPaciente_protesis_profesional`)
    REFERENCES `Paciente_protesis_profesional` (`idPaciente_protesis_profesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paciente_protesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente_protesis` (
  `idPaciente_protesis` INT NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT NOT NULL,
  `Protesis_Serial_protesis` INT NOT NULL,
  PRIMARY KEY (`idPaciente_protesis`),
  INDEX `fk_Paciente_protesis_Paciente_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Paciente_protesis_Protesis1_idx` (`Protesis_Serial_protesis` ASC),
  CONSTRAINT `fk_Paciente_protesis_Paciente`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_protesis_Protesis1`
    FOREIGN KEY (`Protesis_Serial_protesis`)
    REFERENCES `Protesis` (`Serial_protesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paciente_profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente_profesional` (
  `idPaciente_profesional` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Profesionales_idProfesionales` INT NOT NULL,
  PRIMARY KEY (`idPaciente_profesional`),
  INDEX `fk_Paciente_profesional_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Paciente_profesional_Profesionales1_idx` (`Profesionales_idProfesionales` ASC),
  CONSTRAINT `fk_Paciente_profesional_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_profesional_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales`)
    REFERENCES `Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
